spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres?currentSchema=validacoes
    username: postgres
    password: miucho123

    hikari:
      connection-timeout: 5000
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 600000
      max-lifetime: 600000

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update

      connection:
        provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider